FROM phusion/baseimage:0.9.22

MAINTAINER Pascal Brueckner <pascal.brueckner@sylence.cc>

ADD utils/docker/setup_prepare.sh utils/docker/setup_dev.sh /opt/
RUN /bin/bash /opt/setup_prepare.sh
RUN /bin/bash /opt/setup_dev.sh

ADD utils/docker/my_init.d/00_init_dev_env.sh /etc/my_init.d/

EXPOSE 80 443

CMD ["/sbin/my_init"]