services:
  sensor:
    environment:
    - PREV_PREFIX
    - HOST_PWD
    image: honeysens/sensorx86:18.12.01
    privileged: true
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.host.sock
    - ${HOST_PWD}:/mnt
    - ${HOST_PWD}/conf:/etc/manager
    - docker_overlay:/var/lib/docker
version: '3'
volumes:
  docker_overlay: null
